import { Metadata } from "next";
import { Footer } from "./_components/footer";
import { Navbar } from "./_components/navbar";

export const metadata: Metadata = {
  title: "TaskFlow",
  description: "Generated by create next app",
};

const MarketingLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="h-full bg-slate-100">
      <Navbar />
      <main className="pb-20 pt-40">{children}</main>
      <Footer />
    </div>
  );
};

export default MarketingLayout;
